# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a671c7a04754a13b63fb4c38514a4c1"
application_url = "https://accommodation-puppy-pierce-temperatures.trycloudflare.com"
embedded = true
name = "order review"
handle = "order-review-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://accommodation-puppy-pierce-temperatures.trycloudflare.com/auth/callback",
  "https://accommodation-puppy-pierce-temperatures.trycloudflare.com/auth/shopify/callback",
  "https://accommodation-puppy-pierce-temperatures.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://accommodation-puppy-pierce-temperatures.trycloudflare.com/order-review"
subpath = "order-review"
prefix = "apps"

[pos]
embedded = false
